version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: medassistant_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_DB: ${POSTGRES_DB:-medassistant}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medassistant-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: medassistant_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-myuser}:${POSTGRES_PASSWORD:-mypassword}@postgres:5432/${POSTGRES_DB:-medassistant}
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - medassistant-net

  frontend:
    image: node:18-alpine
    container_name: medassistant_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3000:3000"
    networks:
      - medassistant-net

volumes:
  postgres_data:

networks:
  medassistant-net:
    driver: bridge
